### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by kevin9r** [ThisIsQasim/WebGPIO#12]
Hello, i tried to use your code and i receive in my browser:
Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

And the application:

```
pi@raspberrypi:~/WebGPIO $ python3 backend.py     
 * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
[2018-06-13 10:43:33,586] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "backend.py", line 29, in main
    'rooms' : updateStates(rooms),
  File "backend.py", line 14, in updateStates
    rooms[i]['Accesories'][j]['State'] = current_accesory.getState()
  File "/home/pi/WebGPIO/lib/accesory.py", line 30, in getState
    returnCode = subprocess.call([timeout + self.value], shell=True)
TypeError: Can't convert 'int' object to str implicitly
192.168.0.140 - - [13/Jun/2018 10:43:33] "GET / HTTP/1.1" 500 -
```

Where is the mistake?

**Comment by ThisIsQasim** [comment]
Can you post your config.yml file?

**Comment by ThisIsQasim** [comment]
Rechecked the `exampleconfig.yml` and it appears it wasn't accurate. I have updated it with the correct file. Please rebase your config based on the new file. Let me know if it doesn't work.

**Comment by kevin9r** [comment]
have delete the old files and clone again but the same: 

`python3 backend.py 
 * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
[2018-06-13 12:02:13,010] ERROR in app: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib/python3/dist-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3/dist-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "backend.py", line 29, in main
    'rooms' : updateStates(rooms),
  File "backend.py", line 14, in updateStates
    rooms[i]['Accesories'][j]['State'] = current_accesory.getState()
  File "/home/pi/WebGPIO/lib/accesory.py", line 29, in getState
    if GPIO.input(self.pin) is settings['ActiveValue']:
RuntimeError: You must setup() the GPIO channel first
192.168.0.140 - - [13/Jun/2018 12:02:13] "GET / HTTP/1.1" 500 -

`

**Comment by ThisIsQasim** [comment]
I have pushed a fix. Pull the new code and try again
